name: NodeJS Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: create zip bundle
        run: | 
           
           zip -r .build/${{github.sha}}.zip .
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zipped-bundle
          path: .build/${{github.sha}}.zip
#             dist
#             !dist/**/*.md
#       - name: Archive code coverage results
#         uses: actions/upload-artifact@v3
#         with:
#           name: code-coverage-report
#           path: output/test/code-coverage.html

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: akhileshns/heroku-deploy@v3.12.12
  #       with:
  #         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
  #         heroku_app_name: 'node-github-action' #Must be unique in Heroku
  #         heroku_email: 'shivay.lamba@scaler.com'
